"""Builder Agent — Money Mode's automated tool-generation agent (V4).

The Builder Agent is triggered by Money Mode when a monetizable idea is
detected.  Its job is to:

1. Generate a Python tool/service scaffold via the engine LLM
2. Submit it to ForgeController for sandbox validation
3. Return the snapshot_id + validation result to Money Mode
4. The tool is deployed only after passing sandbox + ROI analysis

Flow::

    MoneyMode → BuilderAgent.build_tool(idea) →
        engine.generate(scaffold_prompt) →
        forge_controller.submit_change(auto_deploy=False) →
        Returns snapshot_id for manual / auto approval

Usage::

    from agents.builder_agent import get_builder_agent

    ba = get_builder_agent()
    result = ba.build_tool(
        name="email_validator_saas",
        description="SaaS micro-tool that validates email lists via REST API",
        tool_type="saas",
    )
    # result contains snapshot_id, validation, roi_analysis
"""
from __future__ import annotations

import logging
import time
from typing import Any

logger = logging.getLogger("agents.builder_agent")


# ── Scaffold templates (engine LLM enriches these when available) ──────────────

_TOOL_TEMPLATES: dict[str, str] = {
    "saas": '''\
"""{{NAME}} — AI Employee auto-generated SaaS micro-tool.

Description: {{DESCRIPTION}}
Generated by: BuilderAgent / Money Mode
"""
from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger("tools.{{SLUG}}")


class {{CLASS}}:
    """{{DESCRIPTION}}"""

    def __init__(self) -> None:
        self._processed: int = 0

    def process(self, payload: Any) -> dict[str, Any]:
        """Main processing entry point."""
        self._processed += 1
        logger.info("{{NAME}} processing item #%d", self._processed)
        # TODO: implement core logic
        return {"status": "ok", "processed": self._processed, "result": None}

    def stats(self) -> dict[str, Any]:
        return {"processed": self._processed}


def get_{{SLUG}}() -> {{CLASS}}:
    return {{CLASS}}()
''',
    "api_wrapper": '''\
"""{{NAME}} — AI Employee auto-generated API wrapper.

Description: {{DESCRIPTION}}
"""
from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger("tools.{{SLUG}}")


class {{CLASS}}:
    """{{DESCRIPTION}}"""

    BASE_URL: str = "https://api.example.com"

    def call(self, endpoint: str, *, params: dict | None = None) -> dict[str, Any]:
        # TODO: replace with real HTTP calls
        logger.info("{{NAME}} calling %s/%s", self.BASE_URL, endpoint)
        return {"endpoint": endpoint, "params": params, "result": None}
''',
    "automation": '''\
"""{{NAME}} — AI Employee auto-generated automation script.

Description: {{DESCRIPTION}}
"""
from __future__ import annotations

import logging

logger = logging.getLogger("tools.{{SLUG}}")


def run_{{SLUG}}(*, target: str = "", options: dict | None = None) -> dict:
    """Run the {{NAME}} automation."""
    options = options or {}
    logger.info("Running {{NAME}} on target=%s", target)
    # TODO: implement automation logic
    return {"target": target, "status": "ok", "result": None}
''',
    "digital_product": '''\
"""{{NAME}} — AI Employee auto-generated digital product.

Description: {{DESCRIPTION}}
"""
from __future__ import annotations


class {{CLASS}}:
    """{{DESCRIPTION}}

    A digital product that can be packaged and sold / distributed.
    """

    def generate(self, **kwargs) -> dict:
        """Generate the product output."""
        # TODO: implement generation logic
        return {"product": "{{NAME}}", "output": None, "kwargs": kwargs}

    def price(self) -> float:
        """Return the suggested retail price in USD."""
        return 0.0    # TODO: set price
''',
}

_DEFAULT_TOOL_TYPES = list(_TOOL_TEMPLATES.keys())


def _fill(template: str, *, name: str, description: str) -> str:
    slug = name.lower().replace(" ", "_").replace("-", "_")
    cls = "".join(w.capitalize() for w in name.replace("-", " ").split())
    return (
        template
        .replace("{{NAME}}", name)
        .replace("{{SLUG}}", slug)
        .replace("{{CLASS}}", cls)
        .replace("{{DESCRIPTION}}", description or f"{name}.")
    )


def _ts() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


class BuilderAgent:
    """Forge-driven automated tool generator for Money Mode.

    Responsibilities:
    - Scaffold new tools from Money Mode ideas
    - Submit them through ForgeController (sandbox + ROI analysis)
    - Report results back to Money Mode for revenue tracking

    Architecture rule: all code passes through ForgeController — never direct disk write.
    """

    def build_tool(
        self,
        *,
        name: str,
        description: str = "",
        tool_type: str = "saas",
        auto_deploy: bool = False,
        tag: str = "",
    ) -> dict[str, Any]:
        """Generate and submit a new tool.

        Args:
            name:        Tool name (used as class/function names).
            description: What the tool does (used in docstring + ROI analysis).
            tool_type:   One of saas | api_wrapper | automation | digital_product.
            auto_deploy: Pass through to ForgeController (non-critical only).
            tag:         Optional version tag.

        Returns:
            Dict with snapshot_id, status, validation, roi_analysis.
        """
        tool_type = tool_type if tool_type in _TOOL_TEMPLATES else "saas"
        logger.info("BuilderAgent building '%s' (type=%s)", name, tool_type)

        # 1. Try to enrich via engine LLM
        code = self._generate_code(name, description, tool_type)

        # 2. Derive target module path
        slug = name.lower().replace(" ", "_").replace("-", "_")
        module = f"tools/{slug}.py"

        # 3. ROI analysis before submission
        roi_analysis = self._roi_analysis(module, description, tool_type)
        logger.info(
            "ROI analysis for '%s': roi_score=%.3f priority=%s",
            name, roi_analysis.get("roi_score", 0), roi_analysis.get("priority", "?"),
        )

        # 4. Submit through ForgeController
        try:
            from core.forge_controller import get_forge_controller
            result = get_forge_controller().submit_change(
                module=module,
                code=code,
                description=f"[MoneyMode/Builder] {description}",
                tag=tag or "v1.0",
                author="builder_agent",
                auto_deploy=auto_deploy,
            )
        except Exception as exc:  # noqa: BLE001
            logger.error("BuilderAgent forge submission failed: %s", exc)
            return {"status": "error", "error": "forge submission failed", "name": name, "ts": _ts()}

        # 5. Record economy task
        self._record_economy(name, success=result.get("status") != "rejected")

        return {
            "name": name,
            "module": module,
            "tool_type": tool_type,
            "roi_analysis": roi_analysis,
            **result,
        }

    def suggest_tools(self, *, context: str = "", limit: int = 5) -> list[dict[str, Any]]:
        """Suggest monetizable tool ideas based on system context.

        Combines economy engine suggestions with pattern-based heuristics.
        """
        suggestions = []

        try:
            from core.economy_engine import get_economy_engine
            improvements = get_economy_engine().suggest_improvements(limit=limit)
            for imp in improvements:
                if imp.get("type") == "optimize":
                    suggestions.append({
                        "idea": f"Optimize {imp.get('agent', 'agent')} task throughput",
                        "tool_type": "automation",
                        "roi_impact": imp.get("roi_impact", 0),
                        "reason": imp.get("reason", ""),
                    })
        except Exception:  # noqa: BLE001
            pass

        # Static pattern suggestions
        keywords = context.lower()
        if "email" in keywords:
            suggestions.append({"idea": "Email validation SaaS", "tool_type": "saas", "roi_impact": 0.8})
        if "api" in keywords or "webhook" in keywords:
            suggestions.append({"idea": "API monitoring wrapper", "tool_type": "api_wrapper", "roi_impact": 0.6})
        if "data" in keywords or "scrape" in keywords:
            suggestions.append({"idea": "Data extraction automation", "tool_type": "automation", "roi_impact": 0.7})

        suggestions.sort(key=lambda s: s.get("roi_impact", 0), reverse=True)
        return suggestions[:limit]

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_code(self, name: str, description: str, tool_type: str) -> str:
        """Try to use engine LLM; fall back to template scaffold."""
        template = _TOOL_TEMPLATES.get(tool_type, _TOOL_TEMPLATES["saas"])
        scaffold = _fill(template, name=name, description=description)

        try:
            from engine.api import generate
            prompt = (
                f"Generate a clean Python module for: {name}\n"
                f"Description: {description}\n"
                f"Type: {tool_type}\n"
                f"Use this scaffold as the base:\n\n{scaffold}\n\n"
                "Return only valid, complete Python code."
            )
            generated = generate(prompt, context={"tool_type": tool_type})
            if generated and len(generated) > 50:
                return str(generated)
        except Exception:  # noqa: BLE001
            pass

        return scaffold

    @staticmethod
    def _roi_analysis(module: str, description: str, tool_type: str) -> dict[str, Any]:
        try:
            from core.forge_controller import get_forge_controller
            return get_forge_controller().profit_impact_analysis(
                module=module,
                description=description,
                change_type="tool",
            )
        except Exception:  # noqa: BLE001
            return {"roi_score": 0.5, "priority": "medium"}

    @staticmethod
    def _record_economy(name: str, *, success: bool) -> None:
        try:
            from core.economy_engine import get_economy_engine
            get_economy_engine().record_task(
                agent="builder_agent",
                task_id=f"build:{name}",
                cost=20,
                value=100 if success else 0,
                success=success,
                description=f"Built tool: {name}",
            )
        except Exception:  # noqa: BLE001
            pass


# ── Singleton ─────────────────────────────────────────────────────────────────

_instance: BuilderAgent | None = None
_instance_lock = __import__("threading").Lock()


def get_builder_agent() -> BuilderAgent:
    """Return the process-wide BuilderAgent singleton."""
    global _instance
    with _instance_lock:
        if _instance is None:
            _instance = BuilderAgent()
    return _instance
