"""Ascend Forge Builder — generate project scaffolds via LLM.

Supports four target types:
  fastapi_app   — Python FastAPI service
  workflow      — LangGraph workflow module
  agent         — AI-Employee agent directory
  frontend_page — React JSX page component
"""
from __future__ import annotations

import json
import logging
import os
import re
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_BUILD_DIR = Path("state/build_outputs")

_SCAFFOLD_PROMPTS: dict[str, str] = {
    "fastapi_app": (
        "You are a senior Python backend engineer. Generate a production-ready FastAPI application "
        "based on the following spec. Return ONLY a JSON object with this structure:\n"
        '{{"files": [{{"path": "...", "content": "..."}}], "readme": "...", "install_cmd": "pip install fastapi uvicorn"}}\n'
        "Include main.py, models.py, routes.py, and requirements.txt at minimum.\n\nSpec: {spec}"
    ),
    "workflow": (
        "You are a LangGraph expert. Generate a complete workflow module based on the following spec. "
        "Return ONLY a JSON object:\n"
        '{{"files": [{{"path": "...", "content": "..."}}], "readme": "...", "install_cmd": "pip install langgraph"}}\n'
        "Include __init__.py, graph.py, nodes.py. Each file must be runnable Python.\n\nSpec: {spec}"
    ),
    "agent": (
        "You are an AI systems architect. Generate an AI-Employee compatible agent directory. "
        "Return ONLY a JSON object:\n"
        '{{"files": [{{"path": "...", "content": "..."}}], "readme": "...", "install_cmd": ""}}\n'
        "Include {name}/{name}.py (BaseAgent subclass), {name}/run.sh, {name}/requirements.txt.\n\nSpec: {spec}"
    ),
    "frontend_page": (
        "You are a senior React developer. Generate a complete JSX page component. "
        "Return ONLY a JSON object:\n"
        '{{"files": [{{"path": "...", "content": "..."}}], "readme": "...", "install_cmd": ""}}\n'
        "Use functional components with hooks. No TypeScript. Use inline styles.\n\nSpec: {spec}"
    ),
}


def _parse_llm_response(response: str) -> dict[str, Any]:
    """Extract JSON from LLM response — handles both raw JSON and fenced blocks."""
    # Try raw parse first
    stripped = response.strip()
    try:
        return json.loads(stripped)
    except Exception:
        pass

    # Try JSON fenced block
    m = re.search(r"```(?:json)?\n(.*?)```", stripped, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except Exception:
            pass

    # Return a minimal stub so the caller always gets a dict
    logger.warning("ForgeBuilder: could not parse LLM response as JSON; returning stub")
    return {
        "files": [{"path": "output.txt", "content": stripped}],
        "readme": "Generated by Forge Builder",
        "install_cmd": "",
    }


class ForgeBuilder:
    """Generate project scaffolds from a natural-language spec."""

    def __init__(self, engine=None) -> None:
        self._engine = engine

    def _get_engine(self):
        if self._engine is not None:
            return self._engine
        from neural_brain.core.consciousness_engine import get_engine
        return get_engine()

    def generate_project(
        self,
        spec: str,
        project_name: str,
        target_type: str = "fastapi_app",
    ) -> dict[str, Any]:
        """Generate files for *project_name* based on *spec* and *target_type*.

        Returns:
            {files: [{path, content}], readme: str, install_cmd: str, project_name: str}
        """
        from neural_brain.api.node_bridge import emit

        template = _SCAFFOLD_PROMPTS.get(target_type, _SCAFFOLD_PROMPTS["fastapi_app"])
        prompt = template.format(spec=spec, name=project_name)

        start = time.time()
        try:
            engine = self._get_engine()
            llm_result = engine.process_input(
                f"[FORGE_BUILD] Generate scaffold. target={target_type} project={project_name}\n\n{prompt}",
                user_id="forge_builder",
            )
            result = {"output": llm_result.get("output", ""), "status": "ok" if "error" not in llm_result else "error"}
        except Exception as exc:
            logger.error("ForgeBuilder LLM call failed: %s", exc)
            result = {"status": "error", "error": str(exc)}

        output_text = result.get("output") or ""
        parsed = _parse_llm_response(output_text) if output_text else {
            "files": [], "readme": "LLM unavailable", "install_cmd": "",
        }

        # Write files to disk via artifact_manager (canonical output path)
        from core.artifact_manager import create_artifact
        project_dir = _BUILD_DIR / project_name
        project_dir.mkdir(parents=True, exist_ok=True)
        written: list[dict[str, str]] = []
        for f in parsed.get("files", []):
            safe_name = Path(f.get("path", "output.txt")).name
            fname = f"forge_{project_name}_{safe_name}"
            try:
                meta = create_artifact(
                    f.get("content", ""),
                    name=fname,
                    artifact_type="forge_build",
                    source=f"forge:{target_type}",
                )
                written.append({"path": meta["path"], "content": f.get("content", ""), "artifact_id": meta["id"]})
            except Exception as exc:
                logger.warning("ForgeBuilder: could not write %s: %s", fname, exc)

        latency_ms = (time.time() - start) * 1000
        emit("nb:forge_build_complete", {
            "project_name": project_name,
            "target_type": target_type,
            "file_count": len(written),
            "latency_ms": round(latency_ms, 1),
        })

        return {
            "files": written,
            "readme": parsed.get("readme", ""),
            "install_cmd": parsed.get("install_cmd", ""),
            "project_name": project_name,
            "target_type": target_type,
            "latency_ms": round(latency_ms, 1),
        }
