"""Tests for Agent Output Schema Validation.

Covers:
  - AgentOutput base schema (valid, invalid agent ID, blank content, bad ts)
  - Domain-specific schemas (FinancialOutput disclaimer enforcement)
  - AGENT_SCHEMA_REGISTRY completeness and mapping
  - get_schema_for_agent fallback to GenericAgentOutput
  - OutputValidationMiddleware.validate() success and failure paths
  - OutputValidationMiddleware.validate_or_fallback() success and failure paths
  - Fallback response constant
  - Singleton identity
  - server.py integration (lazy loader, validation call, API endpoints)
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_DIR = REPO_ROOT / "runtime"

if str(RUNTIME_DIR) not in sys.path:
    sys.path.insert(0, str(RUNTIME_DIR))

from pydantic import ValidationError

from core.agent_output_schemas import (
    AGENT_SCHEMA_REGISTRY,
    AgentOutput,
    BrandOutput,
    CompanyOutput,
    ContentOutput,
    EcomOutput,
    EngineeringOutput,
    FinancialOutput,
    GenericAgentOutput,
    GrowthOutput,
    HROutput,
    LeadOutput,
    OrchestratorOutput,
    OutreachOutput,
    ProjectOutput,
    ResearchOutput,
    SalesOutput,
    FALLBACK_RESPONSE,
    OutputValidationMiddleware,
    get_schema_for_agent,
    get_schema_validator,
)

# ── Helpers ───────────────────────────────────────────────────────────────────

def _make_output(**kwargs) -> dict:
    defaults = {
        "agent": "recruiter",
        "content": "Candidate A is recommended because they have the required skills.",
        "ts": "2026-01-01T12:00:00Z",
        "model": "gpt-4o",
        "user_id": "user:test",
    }
    defaults.update(kwargs)
    return defaults


_FINANCIAL_CONTENT = (
    "Market signal analysis. ⚠️  FINANCIAL DISCLAIMER: This output is generated by an AI "
    "system and is for informational purposes only. It does NOT constitute financial advice."
)


# ═══════════════════════════════════════════════════════════════════════════════
# AgentOutput base validation
# ═══════════════════════════════════════════════════════════════════════════════

class TestAgentOutputBase:
    def test_valid_output_parses(self):
        out = AgentOutput(**_make_output())
        assert out.agent == "recruiter"
        assert out.content != ""

    def test_invalid_agent_id_raises(self):
        with pytest.raises(ValidationError):
            AgentOutput(**_make_output(agent="bad agent!"))

    def test_agent_id_too_long_raises(self):
        with pytest.raises(ValidationError):
            AgentOutput(**_make_output(agent="a" * 65))

    def test_agent_id_with_hyphen_and_underscore_ok(self):
        out = AgentOutput(**_make_output(agent="my-agent_v2"))
        assert out.agent == "my-agent_v2"

    def test_empty_content_raises(self):
        with pytest.raises(ValidationError):
            AgentOutput(**_make_output(content=""))

    def test_blank_content_raises(self):
        with pytest.raises(ValidationError):
            AgentOutput(**_make_output(content="   "))

    def test_content_too_long_raises(self):
        with pytest.raises(ValidationError):
            AgentOutput(**_make_output(content="x" * 50_001))

    def test_content_at_max_length_ok(self):
        out = AgentOutput(**_make_output(content="x" * 50_000))
        assert len(out.content) == 50_000

    def test_invalid_ts_raises(self):
        with pytest.raises(ValidationError):
            AgentOutput(**_make_output(ts="not-a-date"))

    def test_empty_ts_allowed(self):
        out = AgentOutput(**_make_output(ts=""))
        assert out.ts == ""

    def test_valid_ts_formats(self):
        for ts in ("2026-01-01T12:00:00Z", "2026-06-15T08:30:00+01:00"):
            out = AgentOutput(**_make_output(ts=ts))
            assert out.ts == ts

    def test_default_fields_have_defaults(self):
        out = AgentOutput(agent="recruiter", content="response")
        assert out.model == ""
        assert out.user_id == ""
        assert out.metadata == {}

    def test_extra_fields_allowed(self):
        out = AgentOutput(**_make_output(), custom_field="hello")
        assert out.model_extra.get("custom_field") == "hello"


# ═══════════════════════════════════════════════════════════════════════════════
# FinancialOutput — disclaimer enforcement
# ═══════════════════════════════════════════════════════════════════════════════

class TestFinancialOutput:
    def test_valid_with_disclaimer(self):
        out = FinancialOutput(**_make_output(
            agent="turbo-quant",
            content=_FINANCIAL_CONTENT,
        ))
        assert out.agent == "turbo-quant"

    def test_missing_disclaimer_raises(self):
        with pytest.raises(ValidationError, match="disclaimer"):
            FinancialOutput(**_make_output(
                agent="turbo-quant",
                content="Just trade everything now.",
            ))

    def test_disclaimer_case_insensitive(self):
        out = FinancialOutput(**_make_output(
            agent="finance-wizard",
            content="Some analysis. Not constitute financial advice of any kind.",
        ))
        assert out.agent == "finance-wizard"


# ═══════════════════════════════════════════════════════════════════════════════
# Domain schemas inherit from AgentOutput
# ═══════════════════════════════════════════════════════════════════════════════

class TestDomainSchemas:
    @pytest.mark.parametrize("schema_cls", [
        OrchestratorOutput, LeadOutput, OutreachOutput, SalesOutput,
        ContentOutput, BrandOutput, ResearchOutput, HROutput,
        EngineeringOutput, GrowthOutput, EcomOutput, ProjectOutput,
        CompanyOutput, GenericAgentOutput,
    ])
    def test_all_inherit_from_agent_output(self, schema_cls):
        assert issubclass(schema_cls, AgentOutput)

    def test_hr_output_parses(self):
        out = HROutput(**_make_output(agent="recruiter"))
        assert isinstance(out, HROutput)

    def test_research_output_parses(self):
        out = ResearchOutput(**_make_output(agent="web-researcher"))
        assert isinstance(out, ResearchOutput)


# ═══════════════════════════════════════════════════════════════════════════════
# AGENT_SCHEMA_REGISTRY
# ═══════════════════════════════════════════════════════════════════════════════

class TestAgentSchemaRegistry:
    def test_registry_is_dict(self):
        assert isinstance(AGENT_SCHEMA_REGISTRY, dict)

    def test_all_values_are_agent_output_subclasses(self):
        for agent_id, cls in AGENT_SCHEMA_REGISTRY.items():
            assert issubclass(cls, AgentOutput), f"Schema for {agent_id!r} is not AgentOutput subclass"

    def test_key_agents_registered(self):
        key_agents = [
            "task-orchestrator", "lead-generator", "recruiter", "hr-manager",
            "finance-wizard", "turbo-quant", "arbitrage-bot",
            "brand-strategist", "web-researcher", "social-media-manager",
            "engineering-assistant", "growth-hacker", "ecom-agent",
            "project-manager", "company-builder",
        ]
        for agent_id in key_agents:
            assert agent_id in AGENT_SCHEMA_REGISTRY, f"{agent_id!r} missing from registry"

    def test_financial_agents_use_financial_output(self):
        financial = ["turbo-quant", "arbitrage-bot", "polymarket-trader", "signal-community", "finance-wizard"]
        for agent_id in financial:
            assert AGENT_SCHEMA_REGISTRY.get(agent_id) is FinancialOutput, \
                f"{agent_id!r} should use FinancialOutput"

    def test_hr_agents_use_hr_output(self):
        assert AGENT_SCHEMA_REGISTRY["recruiter"] is HROutput
        assert AGENT_SCHEMA_REGISTRY["hr-manager"] is HROutput


# ═══════════════════════════════════════════════════════════════════════════════
# get_schema_for_agent
# ═══════════════════════════════════════════════════════════════════════════════

class TestGetSchemaForAgent:
    def test_registered_agent_returns_correct_schema(self):
        assert get_schema_for_agent("recruiter") is HROutput
        assert get_schema_for_agent("turbo-quant") is FinancialOutput
        assert get_schema_for_agent("web-researcher") is ResearchOutput

    def test_unknown_agent_falls_back_to_generic(self):
        assert get_schema_for_agent("totally-unknown-agent") is GenericAgentOutput

    def test_empty_string_falls_back_to_generic(self):
        assert get_schema_for_agent("") is GenericAgentOutput


# ═══════════════════════════════════════════════════════════════════════════════
# OutputValidationMiddleware
# ═══════════════════════════════════════════════════════════════════════════════

class TestOutputValidationMiddleware:
    def _mw(self) -> OutputValidationMiddleware:
        return OutputValidationMiddleware()

    # ── validate() ────────────────────────────────────────────────────────────

    def test_validate_success(self):
        mw = self._mw()
        out = mw.validate("recruiter", "Candidate A is best.", ts="2026-01-01T00:00:00Z")
        assert isinstance(out, HROutput)
        assert out.agent == "recruiter"

    def test_validate_raises_on_empty_content(self):
        mw = self._mw()
        with pytest.raises(ValidationError):
            mw.validate("recruiter", "")

    def test_validate_raises_on_invalid_agent_id(self):
        mw = self._mw()
        with pytest.raises(ValidationError):
            mw.validate("bad agent!!", "some content")

    def test_validate_raises_on_financial_without_disclaimer(self):
        mw = self._mw()
        with pytest.raises(ValidationError):
            mw.validate("turbo-quant", "Buy everything now.", ts="2026-01-01T00:00:00Z")

    def test_validate_financial_with_disclaimer(self):
        mw = self._mw()
        out = mw.validate("turbo-quant", _FINANCIAL_CONTENT, ts="2026-01-01T00:00:00Z")
        assert isinstance(out, FinancialOutput)

    def test_validate_injects_ts_when_empty(self):
        mw = self._mw()
        out = mw.validate("recruiter", "Candidate response")
        assert out.ts != ""

    # ── validate_or_fallback() ────────────────────────────────────────────────

    def test_validate_or_fallback_success_returns_output(self):
        mw = self._mw()
        result, fallback = mw.validate_or_fallback("recruiter", "Candidate A is best.")
        assert result is not None
        assert fallback == ""

    def test_validate_or_fallback_failure_returns_fallback(self):
        mw = self._mw()
        result, fallback = mw.validate_or_fallback("recruiter", "")
        assert result is None
        assert fallback == FALLBACK_RESPONSE

    def test_validate_or_fallback_unknown_agent_uses_generic_schema(self):
        mw = self._mw()
        result, fallback = mw.validate_or_fallback("my-custom-agent", "Some output")
        assert result is not None
        assert isinstance(result, GenericAgentOutput)
        assert fallback == ""

    def test_validate_or_fallback_financial_no_disclaimer(self):
        mw = self._mw()
        result, fallback = mw.validate_or_fallback("turbo-quant", "Buy now!")
        assert result is None
        assert fallback == FALLBACK_RESPONSE

    def test_validate_or_fallback_financial_with_disclaimer(self):
        mw = self._mw()
        result, fallback = mw.validate_or_fallback("turbo-quant", _FINANCIAL_CONTENT)
        assert result is not None
        assert fallback == ""

    # ── Singleton ─────────────────────────────────────────────────────────────

    def test_singleton_same_instance(self):
        a = get_schema_validator()
        b = get_schema_validator()
        assert a is b

    # ── Fallback constant ─────────────────────────────────────────────────────

    def test_fallback_response_is_nonempty_string(self):
        assert isinstance(FALLBACK_RESPONSE, str)
        assert len(FALLBACK_RESPONSE) > 10


# ═══════════════════════════════════════════════════════════════════════════════
# server.py integration (static analysis)
# ═══════════════════════════════════════════════════════════════════════════════

class TestServerSchemaIntegration:
    def _src(self) -> str:
        return (REPO_ROOT / "runtime" / "agents" / "problem-solver-ui" / "server.py").read_text()

    def test_get_schema_validator_loader_defined(self):
        assert "_get_schema_validator" in self._src()

    def test_agent_output_schemas_imported(self):
        assert "agent_output_schemas" in self._src()

    def test_validate_or_fallback_called(self):
        assert "validate_or_fallback" in self._src()

    def test_fallback_replaces_response(self):
        src = self._src()
        assert "_fallback" in src and "response = _fallback" in src

    def test_schema_list_endpoint_registered(self):
        src = self._src()
        assert '"/api/schema"' in src

    def test_schema_agent_endpoint_registered(self):
        src = self._src()
        assert '"/api/schema/{agent_id}"' in src

    def test_schema_validation_error_non_fatal(self):
        src = self._src()
        assert "schema_validator error (non-fatal)" in src

    def test_module_file_exists(self):
        assert (RUNTIME_DIR / "core" / "agent_output_schemas.py").exists()

    def test_validation_happens_before_memory_store(self):
        """Validation block must appear before intel.on_exchange call."""
        src = self._src()
        validate_idx = src.find("validate_or_fallback")
        memory_idx = src.find("intel.on_exchange")
        assert validate_idx < memory_idx, \
            "Validation must happen before memory store"
