"""CEO Briefing Agent — Daily executive briefings generated by AI.

Compiles data from across the AI Employee system and generates
a concise, actionable CEO-level briefing:
  - Recent chat activity and task completions
  - Active agents and system health
  - Leads in pipeline and recent deal movements
  - Revenue metrics from invoices
  - Pending guardrails actions
  - Content calendar and scheduled posts
  - Key alerts and flags

Commands (via chat / WhatsApp / Dashboard):
  brief today                       — today's briefing
  brief generate                    — force-regenerate today's briefing
  brief history                     — list past briefings
  brief status                      — last briefing timestamp

State files:
  ~/.ai-employee/state/ceo-briefings.jsonl
"""
import json
import logging
import os
import sys
import uuid
from datetime import datetime, timezone, date, timedelta
from pathlib import Path
from typing import Optional

AI_HOME = Path(os.environ.get("AI_HOME", str(Path.home() / ".ai-employee")))
BRIEFINGS_FILE = AI_HOME / "state" / "ceo-briefings.jsonl"
CHATLOG = AI_HOME / "state" / "chatlog.jsonl"
GUARDRAILS_LOG = AI_HOME / "state" / "guardrails.jsonl"
CRM_FILE = AI_HOME / "state" / "leads-crm.json"
INVOICES_FILE = AI_HOME / "state" / "invoices.json"
SOCIAL_SCHEDULE = AI_HOME / "state" / "social-schedule.json"

logging.basicConfig(
    level=getattr(logging, os.environ.get("LOG_LEVEL", "WARNING").upper(), logging.WARNING),
    format="%(message)s",
)
logger = logging.getLogger("ceo-briefing")

_ai_router_path = AI_HOME / "agents" / "ai-router"
if str(_ai_router_path) not in sys.path:
    sys.path.insert(0, str(_ai_router_path))

try:
    from ai_router import query_ai_for_agent as _query_ai_for_agent  # type: ignore
    _AI_AVAILABLE = True
except ImportError:
    _AI_AVAILABLE = False

__all__ = [
    "generate_briefing",
    "get_today_briefing",
    "list_briefings",
    "force_regenerate",
]


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _today_str() -> str:
    return date.today().isoformat()


def _load_jsonl(path: Path, limit: int = 100) -> list:
    if not path.exists():
        return []
    lines = []
    try:
        for line in path.read_text().splitlines():
            if line.strip():
                try:
                    lines.append(json.loads(line))
                except Exception:
                    pass
    except Exception:
        pass
    return lines[-limit:]


def _save_briefing(briefing: dict) -> None:
    BRIEFINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(BRIEFINGS_FILE, "a") as f:
        f.write(json.dumps(briefing) + "\n")


def _gather_data() -> dict:
    """Collect metrics from all state files for the briefing."""
    data: dict = {
        "date": _today_str(),
        "chat_messages_today": 0,
        "agents_active": 0,
        "leads_total": 0,
        "leads_by_stage": {},
        "pipeline_value": 0.0,
        "revenue_paid": 0.0,
        "invoices_overdue": 0,
        "invoices_pending": 0,
        "social_posts_today": 0,
        "guardrail_flags": 0,
        "pending_actions": 0,
    }

    # Chat messages today
    today_prefix = _today_str()
    try:
        chat_lines = _load_jsonl(CHATLOG, 500)
        data["chat_messages_today"] = sum(
            1 for m in chat_lines
            if m.get("timestamp", m.get("ts", "")).startswith(today_prefix)
        )
    except Exception:
        pass

    # CRM data
    try:
        if CRM_FILE.exists():
            crm = json.loads(CRM_FILE.read_text())
            leads = crm.get("leads", [])
            data["leads_total"] = len(leads)
            for lead in leads:
                stage = lead.get("stage", "new_lead")
                data["leads_by_stage"][stage] = data["leads_by_stage"].get(stage, 0) + 1
                data["pipeline_value"] += float(lead.get("value", 0))
    except Exception:
        pass

    # Invoice data
    try:
        if INVOICES_FILE.exists():
            inv_data = json.loads(INVOICES_FILE.read_text())
            invoices = inv_data.get("invoices", [])
            for inv in invoices:
                if inv.get("status") == "paid":
                    data["revenue_paid"] += float(inv.get("total", 0))
                elif inv.get("status") == "overdue":
                    data["invoices_overdue"] += 1
                elif inv.get("status") in ("sent", "draft"):
                    data["invoices_pending"] += 1
    except Exception:
        pass

    # Social posts today
    try:
        if SOCIAL_SCHEDULE.exists():
            sched = json.loads(SOCIAL_SCHEDULE.read_text())
            data["social_posts_today"] = sum(
                1 for p in sched.get("posts", [])
                if p.get("published_at", "").startswith(today_prefix)
            )
    except Exception:
        pass

    # Guardrail flags
    try:
        gr_lines = _load_jsonl(GUARDRAILS_LOG, 200)
        data["guardrail_flags"] = sum(
            1 for g in gr_lines
            if g.get("status") == "pending"
        )
    except Exception:
        pass

    return data


def generate_briefing(briefing_date: Optional[str] = None) -> dict:
    """Generate a CEO briefing for the given date (defaults to today)."""
    target_date = briefing_date or _today_str()
    metrics = _gather_data()

    if _AI_AVAILABLE:
        prompt = (
            f"Generate a concise CEO Daily Briefing for {target_date}.\n\n"
            f"Data:\n"
            f"- Chat messages today: {metrics['chat_messages_today']}\n"
            f"- Total leads in CRM: {metrics['leads_total']}\n"
            f"- Pipeline value: ${metrics['pipeline_value']:,.2f}\n"
            f"- Leads by stage: {metrics['leads_by_stage']}\n"
            f"- Revenue (paid invoices): ${metrics['revenue_paid']:,.2f}\n"
            f"- Overdue invoices: {metrics['invoices_overdue']}\n"
            f"- Social posts today: {metrics['social_posts_today']}\n"
            f"- Guardrail flags pending: {metrics['guardrail_flags']}\n\n"
            f"Format as a professional executive briefing with sections:\n"
            f"1. Executive Summary (2-3 sentences)\n"
            f"2. Key Metrics\n"
            f"3. Action Items for Today\n"
            f"4. Risks & Alerts\n\n"
            f"Respond ONLY with valid JSON:\n"
            f'{{"summary": "...", "sections": {{"metrics": "...", '
            f'"action_items": ["..."], "risks": ["..."]}} , "headline": "..."}}'
        )
        try:
            result = _query_ai_for_agent("ceo-briefing", prompt)
            content = result.get("content", result.get("text", ""))
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                parsed = json.loads(content[start:end])
                briefing = {
                    "id": str(uuid.uuid4()),
                    "date": target_date,
                    "headline": parsed.get("headline", f"CEO Briefing — {target_date}"),
                    "summary": parsed.get("summary", ""),
                    "sections": parsed.get("sections", {}),
                    "metrics": metrics,
                    "ai_generated": True,
                    "generated_at": _now_iso(),
                }
                _save_briefing(briefing)
                return briefing
        except Exception:
            pass

    # Fallback: structured briefing without AI
    # Active pipeline = leads not in terminal states (closed_won / closed_lost / unknown stages)
    terminal_stages = {"closed_won", "closed_lost"}
    active_pipeline = sum(
        count for stage, count in metrics["leads_by_stage"].items()
        if stage not in terminal_stages
    )
    briefing = {
        "id": str(uuid.uuid4()),
        "date": target_date,
        "headline": f"CEO Briefing — {target_date}",
        "summary": (
            f"Today's system activity: {metrics['chat_messages_today']} messages processed. "
            f"Pipeline has {active_pipeline} active leads valued at ${metrics['pipeline_value']:,.0f}. "
            f"Total revenue collected: ${metrics['revenue_paid']:,.0f}."
        ),
        "sections": {
            "metrics": (
                f"Leads: {metrics['leads_total']} total | "
                f"Pipeline: ${metrics['pipeline_value']:,.0f} | "
                f"Revenue: ${metrics['revenue_paid']:,.0f} | "
                f"Overdue invoices: {metrics['invoices_overdue']}"
            ),
            "action_items": [
                f"Review {metrics['invoices_overdue']} overdue invoices" if metrics["invoices_overdue"] else "No overdue invoices",
                f"Follow up on {metrics['leads_by_stage'].get('negotiation', 0)} leads in negotiation",
                f"Clear {metrics['guardrail_flags']} pending guardrail actions" if metrics["guardrail_flags"] else "No guardrail flags",
            ],
            "risks": [
                f"{metrics['invoices_overdue']} overdue invoices require attention" if metrics["invoices_overdue"] else "No revenue risks",
                f"{metrics['guardrail_flags']} safety flags pending review" if metrics["guardrail_flags"] else "No safety flags",
            ],
        },
        "metrics": metrics,
        "ai_generated": False,
        "generated_at": _now_iso(),
    }
    _save_briefing(briefing)
    return briefing


def get_today_briefing() -> Optional[dict]:
    """Return today's cached briefing, or generate a new one."""
    today = _today_str()
    lines = _load_jsonl(BRIEFINGS_FILE, 30)
    for briefing in reversed(lines):
        if briefing.get("date") == today:
            return briefing
    return generate_briefing(today)


def list_briefings(limit: int = 30) -> list:
    """Return recent briefings (most recent first)."""
    lines = _load_jsonl(BRIEFINGS_FILE, limit)
    return list(reversed(lines))


def force_regenerate() -> dict:
    """Force-regenerate today's briefing, overwriting the cached version."""
    return generate_briefing(_today_str())
