from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class GeneratedPatch:
    diff: str
    explanation: str
    risk_level: str
    affected_files: list[str]

    def to_dict(self) -> dict[str, Any]:
        return {
            "diff": self.diff,
            "explanation": self.explanation,
            "risk_level": self.risk_level,
            "affected_files": self.affected_files,
        }


class PatchGenerator:
    """LLM-driven unified-diff generator."""

    def __init__(self, repo_root: Path | None = None) -> None:
        self._repo_root = repo_root or self._detect_repo_root()

    @staticmethod
    def _detect_repo_root() -> Path:
        current = Path(__file__).resolve()
        for parent in current.parents:
            if (parent / "package.json").exists():
                return parent
        return current.parents[3]

    def generate(self, issue: dict[str, str]) -> GeneratedPatch:
        severity = (issue.get("severity") or "medium").lower()
        risk = {
            "low": "low",
            "medium": "medium",
            "high": "high",
            "critical": "critical",
        }.get(severity, "medium")

        prompt = (
            "Generate ONLY a unified git diff for this issue. "
            "Do not output prose before the diff.\n"
            f"File: {issue.get('file')}\n"
            f"Issue type: {issue.get('issue_type')}\n"
            f"Severity: {severity}\n"
            f"Suggested fix: {issue.get('suggested_fix')}\n"
        )

        diff = ""
        explanation = "No patch generated"
        try:
            from core.orchestrator import get_llm_client

            raw = get_llm_client().complete(
                prompt=prompt,
                system=(
                    "You are a safe code evolution engine. Return valid unified diff only. "
                    "Never rewrite full files."
                ),
            )
            output = str(raw.get("output", "")).strip()
            diff = self._extract_diff(output)
            explanation = (
                "Patch generated by LLM as unified diff."
                if diff
                else "LLM responded without valid unified diff."
            )
        except Exception as exc:
            explanation = f"Patch generation failed: {exc}"

        affected_files = self._extract_files(diff)
        return GeneratedPatch(
            diff=diff,
            explanation=explanation,
            risk_level=risk,
            affected_files=affected_files,
        )

    @staticmethod
    def _extract_diff(output: str) -> str:
        if not output:
            return ""
        lines = output.splitlines()
        start = 0
        for idx, line in enumerate(lines):
            if line.startswith("diff --git") or line.startswith("--- "):
                start = idx
                break
        diff = "\n".join(lines[start:]).strip()
        if not diff or "@@" not in diff:
            return ""
        return diff + "\n"

    @staticmethod
    def _extract_files(diff_text: str) -> list[str]:
        if not diff_text:
            return []
        files = re.findall(r"\+\+\+ b/(.+)", diff_text)
        if not files:
            files = re.findall(r"diff --git a/(.+?) b/", diff_text)
        return sorted(set(files))
