"""Agent routing constants extracted from server.py.

Contains keyword routing map, per-mode agent lists, aliases, and infra agent set.
"""

ROUTING_MAP = {
  # Core business ops
  "business plan": "company-builder",
  "customer": "qualification-agent",
  "support": "qualification-agent",
  "ticket": "ticket-system",
  # Lead gen & sales
  "prospect": "lead-generator",
  "lead": "lead-generator",
  "outreach": "cold-outreach-assassin",
  "email": "cold-outreach-assassin",
  "cold email": "cold-outreach-assassin",
  "appointment": "appointment-setter",
  "book meeting": "appointment-setter",
  "close deal": "sales-closer-pro",
  "objection": "sales-closer-pro",
  "negotiate": "sales-closer-pro",
  # Content & media
  "blog": "social-media-manager",
  "article": "social-media-manager",
  "seo": "social-media-manager",
  "newsletter": "newsletter-bot",
  "course": "course-creator",
  "video": "faceless-video",
  "youtube": "faceless-video",
  "tiktok": "faceless-video",
  # Social & brand
  "linkedin": "linkedin-growth-hacker",
  "instagram": "social-media-manager",
  "twitter": "social-media-manager",
  "post": "social-media-manager",
  "brand": "brand-strategist",
  "chatbot": "chatbot-builder",
  # Research & analysis
  "competitor": "web-researcher",
  "research": "web-researcher",
  "deepsearch": "financial-deepsearch",
  "market": "financial-deepsearch",
  "analyse": "financial-deepsearch",
  "analyze": "financial-deepsearch",
  "sec filing": "financial-deepsearch",
  "earnings": "financial-deepsearch",
  # Ads & paid media
  "ad copy": "ad-campaign-wizard",
  "ad campaign": "ad-campaign-wizard",
  "meta ads": "ad-campaign-wizard",
  "google ads": "ad-campaign-wizard",
  "ppc": "paid-media-specialist",
  "website": "engineering-assistant",
  # Finance & trading
  "finance": "finance-wizard",
  "revenue": "finance-wizard",
  "trading": "turbo-quant",
  "crypto": "turbo-quant",
  "arbitrage": "arbitrage-bot",
  "signal": "signal-community",
  "polymarket": "polymarket-trader",
  # HR & team
  "hire": "hr-manager",
  "recruit": "recruiter",
  # E-commerce
  "ecommerce": "ecom-agent",
  "shopify": "ecom-agent",
  "print on demand": "print-on-demand",
  "merch": "print-on-demand",
  # Growth & strategy
  "grow": "growth-hacker",
  "conversion": "conversion-rate-optimizer",
  "funnel": "conversion-rate-optimizer",
  "referral": "referral-rocket",
  "partnership": "partnership-matchmaker",
  # Project & ops
  "project": "project-manager",
  "obsidian": "obsidian-memory",
  "memory": "obsidian-memory",
  "goal": "goal-alignment",
  "budget": "budget-tracker",
  "org chart": "org-chart",
}

AGENTS_BY_MODE = {
  "starter": [
    "task-orchestrator",
    "lead-generator",
    "offer-agent",
  ],
  "business": [
    "task-orchestrator",
    "lead-generator",
    "offer-agent",
    "company-builder",
    "brand-strategist",
    "finance-wizard",
    "growth-hacker",
    "project-manager",
    "meeting-intelligence",
    "ceo-briefing",
    "financial-tools",
    # Business-tier feature agents
    "crm-pipeline",
    "email-marketing",
    "invoicing",
    "customer-support",
  ],
  "power": [
    "task-orchestrator",
    "lead-generator",
    "offer-agent",
    "company-builder",
    "brand-strategist",
    "finance-wizard",
    "growth-hacker",
    "project-manager",
    "social-media-manager",
    "paid-media-specialist",
    "qualification-agent",
    "follow-up-agent",
    "appointment-setter",
    "ui-designer",
    "web-researcher",
    "engineering-assistant",
    "ecom-agent",
    "chatbot-builder",
    "creator-agency",
    "recruiter",
    "arbitrage-bot",
    "course-creator",
    "faceless-video",
    "financial-deepsearch",
    "hr-manager",
    "memecoin-creator",
    "mirofish-researcher",
    "newsletter-bot",
    "polymarket-trader",
    "print-on-demand",
    "qa-tester",
    "signal-community",
    "skills-manager",
    "status-reporter",
    "ad-campaign-wizard",
    "cold-outreach-assassin",
    "conversion-rate-optimizer",
    "lead-hunter-elite",
    "linkedin-growth-hacker",
    "partnership-matchmaker",
    "referral-rocket",
    "sales-closer-pro",
    "turbo-quant",
    "ascend-forge",
    "blacklight",
    "hermes-agent",
    "obsidian-memory",
    "lead-intelligence",
    "company-manager",
    "budget-tracker",
    "goal-alignment",
    "governance",
    "org-chart",
    "session-manager",
    "ticket-system",
    "discord-bot",
  ],
}

AGENT_ALIASES = {
  "task-orchestrator": ["task-orchestrator", "orchestrator"],
  "lead-generator": ["lead-generator", "lead-hunter", "lead-hunter-elite"],
  "lead-hunter": ["lead-hunter", "lead-generator", "lead-hunter-elite"],
}

CAPS_ID_ALIASES = {
  "task-orchestrator": ["task-orchestrator", "orchestrator"],
  "lead-generator": ["lead-generator", "lead-hunter"],
  "offer-agent": ["offer-agent", "email-ninja"],
  "social-media-manager": ["social-media-manager", "social-guru", "social-poster"],
  "web-researcher": ["web-researcher", "intel-agent"],
  "ecom-agent": ["ecom-agent", "product-scout", "ecom-dashboard", "order-processor"],
  "chatbot-builder": ["chatbot-builder", "support-bot"],
  "creator-agency": ["creator-agency", "creative-studio"],
  "recruiter": ["recruiter", "hr-manager"],
  "conversion-rate-optimizer": ["conversion-rate-optimizer"],
  "ad-campaign-wizard": ["ad-campaign-wizard"],
  "cold-outreach-assassin": ["cold-outreach-assassin"],
  "partnership-matchmaker": ["partnership-matchmaker"],
  "linkedin-growth-hacker": ["linkedin-growth-hacker"],
  "referral-rocket": ["referral-rocket"],
  "sales-closer-pro": ["sales-closer-pro"],
  "financial-deepsearch": ["financial-deepsearch", "data-analyst"],
  "mirofish-researcher": ["mirofish-researcher", "product-researcher"],
  "skills-manager": ["skills-manager"],
  "arbitrage-bot": ["arbitrage-bot", "bot-dev"],
}

INFRA_AGENTS = {
  "problem-solver-ui",
  "problem-solver",
  "scheduler-runner",
  "status-reporter",
  "auto-updater",
  "discovery",
}
