"""ContentFactory — produce real, multi-platform content and stage it for approval.

Reuses money_mode.content_publish_track (real LLM generation + saved .md artifact)
so there is no duplicate generation logic, then stages each piece in the
PublishQueue as pending_approval. Nothing is ever auto-published.
"""
from __future__ import annotations

import logging
import threading
from typing import Any

from .publish_queue import get_publish_queue

logger = logging.getLogger(__name__)

_DEFAULT_PLATFORMS = ("blog",)
_MAX_PLATFORMS = 8
_MAX_VARIANTS = 5


class ContentFactory:
    """Generate real content artifacts and stage them in the approval-gated queue."""

    def produce(self, brief: dict[str, Any]) -> dict:
        """brief = {topic, platforms?:[...], content_type?, variants?:int}.

        Generates real content per platform (LLM via money_mode), saves an
        artifact, and enqueues each piece as pending_approval. Returns the
        artifacts + queue entries. Honest: real word counts/paths; never posts.
        """
        topic = str((brief or {}).get("topic") or "").strip()
        if not topic:
            return {"ok": False, "error": "topic required"}
        platforms = [str(p) for p in ((brief or {}).get("platforms") or _DEFAULT_PLATFORMS)][:_MAX_PLATFORMS]
        content_type = str((brief or {}).get("content_type") or "post")
        variants = max(1, min(int((brief or {}).get("variants") or 1), _MAX_VARIANTS))

        try:
            from core.money_mode import get_money_mode
            mm = get_money_mode()
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "error": f"content engine unavailable: {exc}"}

        q = get_publish_queue()
        artifacts: list[dict] = []
        queued: list[dict] = []
        real = 0
        for platform in platforms:
            for _ in range(variants):
                try:
                    art = mm.content_publish_track(topic, platform=platform, content_type=content_type)
                except Exception as exc:  # noqa: BLE001 — one failure must not abort the batch
                    artifacts.append({"platform": platform, "status": "error", "error": str(exc)})
                    continue
                artifacts.append({"platform": platform, **{k: art.get(k) for k in
                                  ("artifact", "word_count", "status")}})
                if art.get("status") == "draft":
                    real += 1
                entry = q.enqueue(
                    topic=topic, platform=platform,
                    artifact_path=art.get("artifact"),
                    word_count=int(art.get("word_count") or 0),
                    content_status=str(art.get("status") or "draft"),
                )
                queued.append(entry)

        return {
            "ok": True,
            "topic": topic,
            "platforms": platforms,
            "variants": variants,
            "artifacts": artifacts,            # real saved files + word counts
            "real_drafts": real,               # LLM-generated (not offline template)
            "queued": queued,                  # all pending_approval — nothing posted
            "note": (f"{real}/{len(queued)} pieces generated by the LLM and saved. "
                     "All staged in the publish queue pending your approval — nothing posted."),
        }

    def batch(self, topic: str, variants: int = 3, platform: str = "blog") -> dict:
        """Convenience: N variants of one topic for a single platform."""
        return self.produce({"topic": topic, "platforms": [platform], "variants": variants})

    def generate_media(self, prompt: str, *, model: str = "flux-dev",
                       media_type: str = "image", inputs: dict | None = None,
                       api_key: str | None = None) -> dict:
        """Generate an image/video via the Open-Generative-AI MuAPI engine and stage
        it in the approval-gated queue (never auto-published).

        Honest: returns a real media URL on success, or a real error (e.g. missing
        MUAPI_API_KEY, generation failure) — never a fabricated link.
        """
        prompt = str(prompt or "").strip()
        if not prompt:
            return {"ok": False, "error": "prompt required"}
        try:
            from .muapi_client import generate as _gen, MuapiError
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "error": f"media engine unavailable: {exc}"}
        try:
            out = _gen(model, prompt, inputs=inputs, api_key=api_key)
        except MuapiError as exc:
            return {"ok": False, "error": str(exc), "model": model}
        url = out.get("url")
        if not url:
            return {"ok": False, "error": "MuAPI returned no media url",
                    "model": model, "raw": out.get("raw")}
        entry = get_publish_queue().enqueue(
            topic=prompt[:120], platform=f"media:{media_type}:{model}",
            artifact_path=url, word_count=0, content_status="generated")
        return {"ok": True, "model": model, "media_type": media_type, "url": url,
                "request_id": out.get("request_id"), "queued": entry,
                "note": "Media generated via MuAPI and staged in the publish queue "
                        "pending your approval — nothing posted."}


_instance: ContentFactory | None = None
_instance_lock = threading.Lock()


def get_content_factory() -> ContentFactory:
    global _instance
    with _instance_lock:
        if _instance is None:
            _instance = ContentFactory()
    return _instance
